const iposClosed = [
  {
    id: "paytm-one97",
    name: "One97 Communications Ltd (Paytm)",
    symbol: "PAYTM",
    sector: "FinTech",
    status: "closed",
    openDate: "2021-11-08",
    closeDate: "2021-11-10",
    listingDate: "2021-11-18",
    priceBand: "₹2,080 - ₹2,150",
    issuePrice: 2150,
    lotSize: 6,
    minInvestment: 12900,
    issueSize: "₹18,300 Cr",
    riskLevel: "High",
    description: "Digital payments, financial services, and commerce platform."
  },
  {
    id: "zomato-foodtech",
    name: "Zomato Ltd",
    symbol: "ZOMATO",
    sector: "Food Tech",
    status: "closed",
    openDate: "2021-07-14",
    closeDate: "2021-07-16",
    listingDate: "2021-07-23",
    priceBand: "₹72 - ₹76",
    issuePrice: 76,
    lotSize: 195,
    minInvestment: 14820,
    issueSize: "₹9,375 Cr",
    riskLevel: "High",
    description: "Online food delivery and restaurant discovery platform."
  },
  {
    id: "lic-india",
    name: "Life Insurance Corporation of India",
    symbol: "LICI",
    sector: "Insurance",
    status: "closed",
    openDate: "2022-05-04",
    closeDate: "2022-05-09",
    listingDate: "2022-05-17",
    priceBand: "₹902 - ₹949",
    issuePrice: 949,
    lotSize: 15,
    minInvestment: 14235,
    issueSize: "₹21,000 Cr",
    riskLevel: "Low",
    description: "India’s largest life insurance company."
  },
  {
    id: "nykaa-fsn",
    name: "FSN E-Commerce Ventures Ltd (Nykaa)",
    symbol: "NYKAA",
    sector: "E-Commerce",
    status: "closed",
    openDate: "2021-10-28",
    closeDate: "2021-11-01",
    listingDate: "2021-11-10",
    priceBand: "₹1,085 - ₹1,125",
    issuePrice: 1125,
    lotSize: 12,
    minInvestment: 13500,
    issueSize: "₹5,352 Cr",
    riskLevel: "Medium",
    description: "Beauty, wellness, and fashion e-commerce platform."
  },
  {
    id: "policybazaar-pbfintech",
    name: "PB Fintech Ltd (Policybazaar)",
    symbol: "POLICYBZR",
    sector: "InsurTech",
    status: "closed",
    openDate: "2021-11-01",
    closeDate: "2021-11-03",
    listingDate: "2021-11-15",
    priceBand: "₹940 - ₹980",
    issuePrice: 980,
    lotSize: 15,
    minInvestment: 14700,
    issueSize: "₹5,625 Cr",
    riskLevel: "High",
    description: "Online insurance and lending marketplace."
  },
  {
    id: "tata-technologies",
    name: "Tata Technologies Ltd",
    symbol: "TATATECH",
    sector: "Engineering Services",
    status: "closed",
    openDate: "2023-11-22",
    closeDate: "2023-11-24",
    listingDate: "2023-11-30",
    priceBand: "₹475 - ₹500",
    issuePrice: 500,
    lotSize: 30,
    minInvestment: 15000,
    issueSize: "₹3,042 Cr",
    riskLevel: "Low",
    description: "Engineering and digital solutions for automotive & aerospace."
  },
  {
    id: "ireda",
    name: "Indian Renewable Energy Development Agency",
    symbol: "IREDA",
    sector: "Renewable Energy",
    status: "closed",
    openDate: "2023-11-21",
    closeDate: "2023-11-23",
    listingDate: "2023-11-29",
    priceBand: "₹30 - ₹32",
    issuePrice: 32,
    lotSize: 460,
    minInvestment: 14720,
    issueSize: "₹2,150 Cr",
    riskLevel: "Low",
    description: "Financing arm for renewable energy projects."
  },
  {
    id: "mapmyindia-ceinfo",
    name: "CE Info Systems Ltd (MapMyIndia)",
    symbol: "MAPMYINDIA",
    sector: "Technology",
    status: "closed",
    openDate: "2021-12-09",
    closeDate: "2021-12-13",
    listingDate: "2021-12-21",
    priceBand: "₹1,000 - ₹1,033",
    issuePrice: 1033,
    lotSize: 14,
    minInvestment: 14462,
    issueSize: "₹1,040 Cr",
    riskLevel: "Medium",
    description: "Digital maps, geospatial software, and IoT solutions."
  },
  {
    id: "delhivery",
    name: "Delhivery Ltd",
    symbol: "DELHIVERY",
    sector: "Logistics",
    status: "closed",
    openDate: "2022-05-11",
    closeDate: "2022-05-13",
    listingDate: "2022-05-24",
    priceBand: "₹462 - ₹487",
    issuePrice: 487,
    lotSize: 30,
    minInvestment: 14610,
    issueSize: "₹5,235 Cr",
    riskLevel: "Medium",
    description: "Integrated logistics and supply chain services provider."
  },
  {
    id: "campus-footwear",
    name: "Campus Activewear Ltd",
    symbol: "CAMPUS",
    sector: "Footwear",
    status: "closed",
    openDate: "2022-04-26",
    closeDate: "2022-04-28",
    listingDate: "2022-05-09",
    priceBand: "₹278 - ₹292",
    issuePrice: 292,
    lotSize: 51,
    minInvestment: 14892,
    issueSize: "₹1,400 Cr",
    riskLevel: "Medium",
    description: "Sports and casual footwear manufacturer."
  },
  {
    id: "sbi-cards",
    name: "SBI Cards and Payment Services Ltd",
    symbol: "SBICARD",
    sector: "Financial Services",
    status: "closed",
    openDate: "2020-03-02",
    closeDate: "2020-03-05",
    listingDate: "2020-03-16",
    priceBand: "₹750 - ₹755",
    issuePrice: 755,
    lotSize: 19,
    minInvestment: 14345,
    issueSize: "₹10,341 Cr",
    riskLevel: "Low",
    description: "Credit card issuer and payment services company."
  },
  {
    id: "mazagon-dock",
    name: "Mazagon Dock Shipbuilders Ltd",
    symbol: "MAZDOCK",
    sector: "Defence",
    status: "closed",
    openDate: "2020-09-29",
    closeDate: "2020-10-01",
    listingDate: "2020-10-12",
    priceBand: "₹135 - ₹145",
    issuePrice: 145,
    lotSize: 103,
    minInvestment: 14935,
    issueSize: "₹443 Cr",
    riskLevel: "Low",
    description: "Defense shipbuilding and submarine manufacturing."
  },
  {
    id: "irctc",
    name: "Indian Railway Catering and Tourism Corporation",
    symbol: "IRCTC",
    sector: "Travel & Tourism",
    status: "closed",
    openDate: "2019-09-30",
    closeDate: "2019-10-03",
    listingDate: "2019-10-14",
    priceBand: "₹315 - ₹320",
    issuePrice: 320,
    lotSize: 40,
    minInvestment: 12800,
    issueSize: "₹645 Cr",
    riskLevel: "Low",
    description: "Railway ticketing, catering, and tourism services."
  },
  {
    id: "hdfc-life",
    name: "HDFC Life Insurance Company Ltd",
    symbol: "HDFCLIFE",
    sector: "Insurance",
    status: "closed",
    openDate: "2017-11-07",
    closeDate: "2017-11-09",
    listingDate: "2017-11-17",
    priceBand: "₹275 - ₹290",
    issuePrice: 290,
    lotSize: 51,
    minInvestment: 14790,
    issueSize: "₹8,695 Cr",
    riskLevel: "Low",
    description: "Private life insurance provider in India."
  },
  {
    id: "coal-india",
    name: "Coal India Ltd",
    symbol: "COALINDIA",
    sector: "Mining",
    status: "closed",
    openDate: "2010-10-18",
    closeDate: "2010-10-21",
    listingDate: "2010-11-04",
    priceBand: "₹225 - ₹245",
    issuePrice: 245,
    lotSize: 30,
    minInvestment: 7350,
    issueSize: "₹15,200 Cr",
    riskLevel: "Low",
    description: "World’s largest coal mining company."
  }
];

export default iposClosed;
