const iposUpcoming = [
  {
    id: "flipkart-ecommerce",
    name: "Flipkart E-commerce Ltd",
    symbol: "FLPKRT",
    sector: "E-Commerce",
    status: "upcoming",
    openDate: "2026-02-01",
    closeDate: "2026-02-03",
    listingDate: "2026-02-08",
    priceBand: "₹1380 - ₹1420",
    issuePrice: 1420,
    lotSize: 10,
    minInvestment: 14200,
    issueSize: "₹22,000 Cr",
    riskLevel: "Low",
    description: "Leading Indian e-commerce platform offering a wide range of products."
  },
  {
    id: "phonepe-payments",
    name: "PhonePe Financial Services",
    symbol: "PHONEPE",
    sector: "Fintech",
    status: "upcoming",
    openDate: "2026-02-02",
    closeDate: "2026-02-04",
    listingDate: "2026-02-09",
    priceBand: "₹520 - ₹550",
    issuePrice: 550,
    lotSize: 25,
    minInvestment: 13750,
    issueSize: "₹10,000 Cr",
    riskLevel: "Medium",
    description: "Digital payments and financial services platform."
  },
  {
    id: "dream11-gaming",
    name: "Dream11 Fantasy Sports Ltd",
    symbol: "DREAM11",
    sector: "Gaming",
    status: "upcoming",
    openDate: "2026-02-03",
    closeDate: "2026-02-05",
    listingDate: "2026-02-10",
    priceBand: "₹880 - ₹920",
    issuePrice: 920,
    lotSize: 15,
    minInvestment: 13800,
    issueSize: "₹3,500 Cr",
    riskLevel: "High",
    description: "Fantasy sports gaming and entertainment platform."
  },
  {
    id: "cred-fintech",
    name: "CRED Financial Services",
    symbol: "CRED",
    sector: "Fintech",
    status: "upcoming",
    openDate: "2026-02-04",
    closeDate: "2026-02-06",
    listingDate: "2026-02-11",
    priceBand: "₹680 - ₹720",
    issuePrice: 720,
    lotSize: 20,
    minInvestment: 14400,
    issueSize: "₹6,200 Cr",
    riskLevel: "High",
    description: "Credit card payments and rewards platform."
  },
  {
    id: "bigbasket-groceries",
    name: "BigBasket Grocery Ltd",
    symbol: "BIGBASK",
    sector: "Retail",
    status: "upcoming",
    openDate: "2026-02-05",
    closeDate: "2026-02-07",
    listingDate: "2026-02-12",
    priceBand: "₹450 - ₹480",
    issuePrice: 480,
    lotSize: 30,
    minInvestment: 14400,
    issueSize: "₹7,500 Cr",
    riskLevel: "Medium",
    description: "Online grocery and essentials platform."
  },
  {
    id: "meesho-social-commerce",
    name: "Meesho Social Commerce Ltd",
    symbol: "MEESHO",
    sector: "Social Commerce",
    status: "upcoming",
    openDate: "2026-02-06",
    closeDate: "2026-02-08",
    listingDate: "2026-02-13",
    priceBand: "₹280 - ₹300",
    issuePrice: 300,
    lotSize: 50,
    minInvestment: 15000,
    issueSize: "₹2,800 Cr",
    riskLevel: "High",
    description: "Social commerce platform connecting small sellers and buyers."
  },
  {
    id: "upgrad-education",
    name: "upGrad Education Ltd",
    symbol: "UPGRAD",
    sector: "EdTech",
    status: "upcoming",
    openDate: "2026-02-07",
    closeDate: "2026-02-09",
    listingDate: "2026-02-14",
    priceBand: "₹240 - ₹260",
    issuePrice: 260,
    lotSize: 60,
    minInvestment: 15600,
    issueSize: "₹4,000 Cr",
    riskLevel: "Medium",
    description: "Online higher education and skill development platform."
  },
  {
    id: "policybazaar-broking",
    name: "Policybazaar Insurance Broking Ltd",
    symbol: "PBINS",
    sector: "Insurtech",
    status: "upcoming",
    openDate: "2026-02-08",
    closeDate: "2026-02-10",
    listingDate: "2026-02-15",
    priceBand: "₹920 - ₹960",
    issuePrice: 960,
    lotSize: 15,
    minInvestment: 14400,
    issueSize: "₹3,900 Cr",
    riskLevel: "Medium",
    description: "Insurance comparison and broking platform."
  },
  {
    id: "adani-energy-solutions",
    name: "Adani Energy Solutions Ltd",
    symbol: "ADENRG",
    sector: "Energy",
    status: "upcoming",
    openDate: "2026-02-09",
    closeDate: "2026-02-11",
    listingDate: "2026-02-16",
    priceBand: "₹350 - ₹370",
    issuePrice: 370,
    lotSize: 40,
    minInvestment: 14800,
    issueSize: "₹10,000 Cr",
    riskLevel: "Low",
    description: "Renewable energy generation and solutions."
  },
  {
    id: "tata-infra-growth",
    name: "Tata Infrastructure Growth Ltd",
    symbol: "TATINFRA",
    sector: "Infrastructure",
    status: "upcoming",
    openDate: "2026-02-10",
    closeDate: "2026-02-12",
    listingDate: "2026-02-17",
    priceBand: "₹510 - ₹540",
    issuePrice: 540,
    lotSize: 30,
    minInvestment: 16200,
    issueSize: "₹8,800 Cr",
    riskLevel: "Low",
    description: "Infrastructure development and engineering solutions."
  },
  {
    id: "tata-healthcare-services",
    name: "Tata Healthcare Services Ltd",
    symbol: "TATHEALTH",
    sector: "Healthcare",
    status: "upcoming",
    openDate: "2026-02-11",
    closeDate: "2026-02-13",
    listingDate: "2026-02-18",
    priceBand: "₹730 - ₹760",
    issuePrice: 760,
    lotSize: 20,
    minInvestment: 15200,
    issueSize: "₹9,500 Cr",
    riskLevel: "Low",
    description: "Healthcare service provider and hospital network."
  },
  {
    id: "olacabs-mobility",
    name: "Ola Cabs Mobility Ltd",
    symbol: "OLACAB",
    sector: "Transportation",
    status: "upcoming",
    openDate: "2026-02-12",
    closeDate: "2026-02-14",
    listingDate: "2026-02-19",
    priceBand: "₹85 - ₹95",
    issuePrice: 95,
    lotSize: 150,
    minInvestment: 14250,
    issueSize: "₹4,700 Cr",
    riskLevel: "High",
    description: "App-based transportation and mobility services."
  },
  {
    id: "larsentoubro-engineering",
    name: "Larsen & Toubro Engineering Ltd",
    symbol: "LNTENG",
    sector: "Engineering",
    status: "upcoming",
    openDate: "2026-02-13",
    closeDate: "2026-02-15",
    listingDate: "2026-02-20",
    priceBand: "₹1420 - ₹1450",
    issuePrice: 1450,
    lotSize: 10,
    minInvestment: 14500,
    issueSize: "₹15,000 Cr",
    riskLevel: "Low",
    description: "Engineering and construction services conglomerate."
  },
  {
    id: "bharat-forge-metals",
    name: "Bharat Forge Metals Ltd",
    symbol: "BFRGMET",
    sector: "Manufacturing",
    status: "upcoming",
    openDate: "2026-02-14",
    closeDate: "2026-02-16",
    listingDate: "2026-02-21",
    priceBand: "₹885 - ₹915",
    issuePrice: 915,
    lotSize: 17,
    minInvestment: 15555,
    issueSize: "₹5,500 Cr",
    riskLevel: "Medium",
    description: "Forging and manufacturing solutions provider."
  },
  {
    id: "infosys-ai-solutions",
    name: "Infosys AI Solutions Ltd",
    symbol: "INFYAI",
    sector: "Technology",
    status: "upcoming",
    openDate: "2026-02-15",
    closeDate: "2026-02-17",
    listingDate: "2026-02-22",
    priceBand: "₹1020 - ₹1050",
    issuePrice: 1050,
    lotSize: 10,
    minInvestment: 10500,
    issueSize: "₹12,000 Cr",
    riskLevel: "Low",
    description: "Artificial intelligence-driven software solutions."
  },
  {
    id: "maruti-suzuki-auto",
    name: "Maruti Suzuki Auto Parts Ltd",
    symbol: "MARUPT",
    sector: "Automobile",
    status: "upcoming",
    openDate: "2026-02-16",
    closeDate: "2026-02-18",
    listingDate: "2026-02-23",
    priceBand: "₹680 - ₹710",
    issuePrice: 710,
    lotSize: 20,
    minInvestment: 14200,
    issueSize: "₹7,200 Cr",
    riskLevel: "Low",
    description: "Auto components and parts manufacturing."
  },
    {
    id: "indiamart-b2b-platform",
    name: "IndiaMART B2B Platform Ltd",
    symbol: "INDMART",
    sector: "Marketplace",
    status: "upcoming",
    openDate: "2026-02-17",
    closeDate: "2026-02-19",
    listingDate: "2026-02-24",
    priceBand: "₹8,200 - ₹8,350",
    issuePrice: 8350,
    lotSize: 1,
    minInvestment: 8350,
    issueSize: "₹3,400 Cr",
    riskLevel: "Low",
    description: "India’s largest B2B online marketplace for SMEs."
  },
  {
    id: "oyo-hospitality",
    name: "OYO Hospitality Ltd",
    symbol: "OYO",
    sector: "Hospitality",
    status: "upcoming",
    openDate: "2026-02-18",
    closeDate: "2026-02-20",
    listingDate: "2026-02-25",
    priceBand: "₹68 - ₹72",
    issuePrice: 72,
    lotSize: 200,
    minInvestment: 14400,
    issueSize: "₹8,430 Cr",
    riskLevel: "High",
    description: "Asset-light hospitality and hotel aggregation platform."
  },
  {
    id: "zepto-quick-commerce",
    name: "Zepto Quick Commerce Ltd",
    symbol: "ZEPTO",
    sector: "Quick Commerce",
    status: "upcoming",
    openDate: "2026-02-19",
    closeDate: "2026-02-21",
    listingDate: "2026-02-26",
    priceBand: "₹410 - ₹430",
    issuePrice: 430,
    lotSize: 35,
    minInvestment: 15050,
    issueSize: "₹2,800 Cr",
    riskLevel: "High",
    description: "10-minute grocery and essentials delivery startup."
  },
  {
    id: "lenskart-eyewear",
    name: "Lenskart Eyewear Ltd",
    symbol: "LENSKRT",
    sector: "Retail",
    status: "upcoming",
    openDate: "2026-02-20",
    closeDate: "2026-02-22",
    listingDate: "2026-02-27",
    priceBand: "₹780 - ₹820",
    issuePrice: 820,
    lotSize: 18,
    minInvestment: 14760,
    issueSize: "₹5,000 Cr",
    riskLevel: "Medium",
    description: "Omnichannel eyewear retail and manufacturing brand."
  },
  {
    id: "delhivery-logistics",
    name: "Delhivery Logistics Expansion Ltd",
    symbol: "DELHEX",
    sector: "Logistics",
    status: "upcoming",
    openDate: "2026-02-21",
    closeDate: "2026-02-23",
    listingDate: "2026-02-28",
    priceBand: "₹470 - ₹495",
    issuePrice: 495,
    lotSize: 30,
    minInvestment: 14850,
    issueSize: "₹4,200 Cr",
    riskLevel: "Medium",
    description: "Integrated logistics and supply chain services company."
  },
  {
    id: "byjus-edtech",
    name: "BYJU’S Learning Solutions Ltd",
    symbol: "BYJUS",
    sector: "EdTech",
    status: "upcoming",
    openDate: "2026-02-22",
    closeDate: "2026-02-24",
    listingDate: "2026-03-01",
    priceBand: "₹360 - ₹380",
    issuePrice: 380,
    lotSize: 40,
    minInvestment: 15200,
    issueSize: "₹6,000 Cr",
    riskLevel: "High",
    description: "Digital learning and test preparation platform."
  },
  {
    id: "swiggy-instamart",
    name: "Swiggy Instamart Ltd",
    symbol: "INSTAMT",
    sector: "Quick Commerce",
    status: "upcoming",
    openDate: "2026-02-23",
    closeDate: "2026-02-25",
    listingDate: "2026-03-02",
    priceBand: "₹540 - ₹570",
    issuePrice: 570,
    lotSize: 25,
    minInvestment: 14250,
    issueSize: "₹7,100 Cr",
    riskLevel: "High",
    description: "Instant grocery and daily essentials delivery arm of Swiggy."
  },
  {
    id: "tata-digital",
    name: "Tata Digital Ltd",
    symbol: "TATDIGI",
    sector: "Digital Services",
    status: "upcoming",
    openDate: "2026-02-24",
    closeDate: "2026-02-26",
    listingDate: "2026-03-03",
    priceBand: "₹980 - ₹1,020",
    issuePrice: 1020,
    lotSize: 14,
    minInvestment: 14280,
    issueSize: "₹18,000 Cr",
    riskLevel: "Low",
    description: "Tata Group’s digital commerce and super-app platform."
  },
  {
    id: "snapdeal-ecommerce",
    name: "Snapdeal Marketplace Ltd",
    symbol: "SNAPDL",
    sector: "E-Commerce",
    status: "upcoming",
    openDate: "2026-02-25",
    closeDate: "2026-02-27",
    listingDate: "2026-03-04",
    priceBand: "₹190 - ₹205",
    issuePrice: 205,
    lotSize: 70,
    minInvestment: 14350,
    issueSize: "₹2,300 Cr",
    riskLevel: "Medium",
    description: "Value-focused online marketplace platform."
  }
];

export default iposUpcoming;
