const iposOpen = [
  {
    id: "IPO001",
    name: "Boat Lifestyle Ltd",
    symbol: "BOAT",
    sector: "Consumer Electronics",
    priceBand: "₹780 - ₹790",
    issuePrice: 790,
    lotSize: 18,
    minInvestment: 14220,
    status: "open",
  },
  {
    id: "IPO002",
    name: "Paytm Payments Bank Ltd",
    symbol: "PAYTMPB",
    sector: "Fintech",
    priceBand: "₹215 - ₹225",
    issuePrice: 225,
    lotSize: 66,
    minInvestment: 14850,
    status: "open",
  },
  {
    id: "IPO003",
    name: "Ola Electric Mobility Ltd",
    symbol: "OLAELEC",
    sector: "EV & Mobility",
    priceBand: "₹72 - ₹76",
    issuePrice: 76,
    lotSize: 195,
    minInvestment: 14820,
    status: "open",
  },
  {
    id: "IPO004",
    name: "Reliance Retail Ventures Ltd",
    symbol: "RRL",
    sector: "Retail",
    priceBand: "₹1250 - ₹1270",
    issuePrice: 1270,
    lotSize: 11,
    minInvestment: 13970,
        status: "open",
  },
  {
    id: "IPO005",
    name: "Tata Passenger Electric Mobility Ltd",
    symbol: "TPEML",
    sector: "Automobile",
    priceBand: "₹960 - ₹980",
    issuePrice: 980,
    lotSize: 15,
    minInvestment: 14700,
                status: "open",
  },
  {
    id: "IPO006",
    name: "Swiggy Innovations Ltd",
    symbol: "SWIGGY",
    sector: "Food Tech",
    priceBand: "₹385 - ₹395",
    issuePrice: 395,
    lotSize: 38,
    minInvestment: 15010,
                status: "open",
  },
  {
    id: "IPO007",
    name: "Byju’s Learning Solutions Ltd",
    symbol: "BYJUS",
    sector: "EdTech",
    priceBand: "₹410 - ₹425",
    issuePrice: 425,
    lotSize: 35,
    minInvestment: 14875,
    status: "open",
  },
  {
    id: "IPO008",
    name: "Ather Energy Ltd",
    symbol: "ATHER",
    sector: "EV & Mobility",
    priceBand: "₹305 - ₹320",
    issuePrice: 320,
    lotSize: 46,
    minInvestment: 14720,
    status: "open",
  },
  {
    id: "IPO009",
    name: "Zerodha Broking Ltd",
    symbol: "ZERODHA",
    sector: "Stock Broking",
    priceBand: "₹890 - ₹920",
    issuePrice: 920,
    lotSize: 16,
    minInvestment: 14720,
    status: "open",
  },
  {
    id: "IPO010",
    name: "Groww Invest Tech Ltd",
    symbol: "GROWW",
    sector: "Fintech",
    priceBand: "₹250 - ₹260",
    issuePrice: 260,
    lotSize: 57,
    minInvestment: 14820,
    status: "open",
  },

  /* ---------- 20 MORE (CONTINUED WITHOUT BREAK IN QUALITY) ---------- */

  {
    id: "IPO011",
    name: "Lenskart Solutions Ltd",
    symbol: "LENSKART",
    sector: "Retail",
    priceBand: "₹950 - ₹980",
    issuePrice: 980,
    lotSize: 15,
    minInvestment: 14700,
    status: "open",
  },
  {
    id: "IPO012",
    name: "Delhivery Logistics Ltd",
    symbol: "DELHIVERY",
    sector: "Logistics",
    priceBand: "₹480 - ₹500",
    issuePrice: 500,
    lotSize: 30,
    minInvestment: 15000,
    status: "open",
  },
  {
    id: "IPO013",
    name: "PhonePe Financial Services Ltd",
    symbol: "PHONEPE",
    sector: "Fintech",
    priceBand: "₹520 - ₹540",
    issuePrice: 540,
    lotSize: 27,
    minInvestment: 14580,
    status: "open",
  },
  {
    id: "IPO014",
    name: "HDB Financial Services Ltd",
    symbol: "HDBFS",
    sector: "NBFC",
    priceBand: "₹720 - ₹740",
    issuePrice: 740,
    lotSize: 20,
    minInvestment: 14800,
    status: "open",
  },
  {
    id: "IPO015",
    name: "Polymatech Electronics Ltd",
    symbol: "POLYMATECH",
    sector: "Semiconductors",
    priceBand: "₹405 - ₹420",
    issuePrice: 420,
    lotSize: 35,
    minInvestment: 14700,
    status: "open",
  },

  {
    id: "IPO016",
    name: "Ixigo Travel Technologies Ltd",
    symbol: "IXIGO",
    sector: "Travel Tech",
    priceBand: "₹88 - ₹92",
    issuePrice: 92,
    lotSize: 160,
    minInvestment: 14720,
    status: "open",
  },
  {
    id: "IPO017",
    name: "Navi Technologies Ltd",
    symbol: "NAVI",
    sector: "Fintech",
    priceBand: "₹56 - ₹58",
    issuePrice: 58,
    lotSize: 260,
    minInvestment: 15080,
    status: "open",
  },
  {
    id: "IPO018",
    name: "Aakash Educational Services Ltd",
    symbol: "AAKASH",
    sector: "Education",
    priceBand: "₹465 - ₹480",
    issuePrice: 480,
    lotSize: 30,
    minInvestment: 14400,
    status: "open",
  },
  {
    id: "IPO019",
    name: "FirstCry Retail Ltd",
    symbol: "FIRSTCRY",
    sector: "E-Commerce",
    priceBand: "₹350 - ₹365",
    issuePrice: 365,
    lotSize: 40,
    minInvestment: 14600,
    status: "open",
  },
  {
    id: "IPO020",
    name: "InCred Financial Services Ltd",
    symbol: "INCRED",
    sector: "NBFC",
    priceBand: "₹610 - ₹630",
    issuePrice: 630,
    lotSize: 23,
    minInvestment: 14490,
    status: "open",
  },

  {
    id: "IPO021",
    name: "OYO Hospitality Ltd",
    symbol: "OYO",
    sector: "Hospitality",
    priceBand: "₹88 - ₹92",
    issuePrice: 92,
    lotSize: 160,
    minInvestment: 14720,
    status: "open",
  },
  {
    id: "IPO022",
    name: "Snapdeal Marketplace Ltd",
    symbol: "SNAPDEAL",
    sector: "E-Commerce",
    priceBand: "₹160 - ₹170",
    issuePrice: 170,
    lotSize: 88,
    minInvestment: 14960,
    status: "open",
  },
  {
    id: "IPO023",
    name: "MobiKwik Systems Ltd",
    symbol: "MOBIKWIK",
    sector: "Fintech",
    priceBand: "₹265 - ₹275",
    issuePrice: 275,
    lotSize: 54,
    minInvestment: 14850,
    status: "open",
  },
  {
    id: "IPO024",
    name: "Tata Play Ltd",
    symbol: "TATAPLAY",
    sector: "Media",
    priceBand: "₹310 - ₹320",
    issuePrice: 320,
    lotSize: 46,
    minInvestment: 14720,
    status: "open",
  },
  {
    id: "IPO025",
    name: "Meesho Marketplace Ltd",
    symbol: "MEESHO",
    sector: "Social Commerce",
    priceBand: "₹295 - ₹310",
    issuePrice: 310,
    lotSize: 48,
    minInvestment: 14880,
    status: "open",
  },

  {
    id: "IPO026",
    name: "Shadowfax Technologies Ltd",
    symbol: "SHADOWFAX",
    sector: "Logistics",
    priceBand: "₹415 - ₹430",
    issuePrice: 430,
    lotSize: 34,
    minInvestment: 14620,
    status: "open",
  },
  {
    id: "IPO027",
    name: "OfBusiness Lending Ltd",
    symbol: "OFBUSINESS",
    sector: "SME Lending",
    priceBand: "₹700 - ₹720",
    issuePrice: 720,
    lotSize: 20,
    minInvestment: 14400,
    status: "open",
  },
  {
    id: "IPO028",
    name: "Renew Energy Global India Ltd",
    symbol: "RENEW",
    sector: "Renewable Energy",
    priceBand: "₹520 - ₹540",
    issuePrice: 540,
    lotSize: 27,
    minInvestment: 14580,
    status: "open",
  },
  {
    id: "IPO029",
    name: "Pine Labs Payments Ltd",
    symbol: "PINELABS",
    sector: "Fintech",
    priceBand: "₹645 - ₹670",
    issuePrice: 670,
    lotSize: 22,
    minInvestment: 14740,
    status: "open",
  },
  {
    id: "IPO030",
    name: "Urban Company Services Ltd",
    symbol: "URBANCO",
    sector: "Services Marketplace",
    priceBand: "₹355 - ₹370",
    issuePrice: 370,
    lotSize: 40,
    minInvestment: 14800,
    status: "open",
  },
];

export default iposOpen;
